# :blog:
#     :polling:
#         :posts:
#             :url: 'http://www.bitovi.com/blog.rss'
#             :interval: 1

# :forum:
#     :polling:
#         :general:
#             :url: 'https://forum.javascriptmvc.com/feed'
#             :interval: 1
#         :questions:
#             :url: 'https://forum.javascriptmvc.com/feed/filter/questions'
#             :interval: 1

# :stackexchange:
#     :data:
#         :auth: &stackexchange_auth
#             :access_token: "ai*6QcDJ8qVkQKqxXbUARw))"
#             :key: "8EAiwRhHlupc0Z1aV3SCVg(("

#     :polling:
#         :canjs_questions:
#             :interval: 1
#             :url: "https://api.stackexchange.com/2.2/questions"
#             :params:
#                 <<: &stackexchange_auth
#                 :site: "stackoverflow"
#                 :tagged: "canjs"
#                 :filter: "_GZ-2_GIz-dSc9CjKwGP4UEOutlPKHh*F)x8rj8B2kRb1dHxpaJFC5Upazs"
#         :javascriptmvc_questions:
#             :interval: 1
#             :url: "https://api.stackexchange.com/2.2/questions"
#             :params:
#                 <<: &stackexchange_auth
#                 :site: "stackoverflow"
#                 :tagged: "javascriptmvc"
#                 :filter: "_GZ-2_GIz-dSc9CjKwGP4UEOutlPKHh*F)x8rj8B2kRb1dHxpaJFC5Upazs"

:public_streams:
    :twitter:
        :api_key: 'huCmG0TZ7vs6leLqLNlGQ'
        :api_secret: 'X4mx1qgGlZ1BVIFFUDB4kzrE1NV7t0nAjx5hY5tQOWQ'
    :meetup:
        :api_key: '663a24605a37767831495d6332546b4a'

:brands:
    :veljko:
        :facebook:
            :token: 'CAAKROn3HV5UBAOIGG46iqorPS4Wy70DIcESQXZAsF9TkB2MRH2gWZAmNzOgGAXQAIpAwTMSQCCpXvBKwLdZAxUHKN0GZCFjXW3dIKm4XgQm12Yo7sfp9JZBSfvpLjdO32rCn7HjEHRT6pZBCzBG8AjwV6TGVgi36DEEnAAAMg5oTheNk66rZAka8GnIIyN3UzgZD'
            :pages:
                - :id: '192366630868826'
                  :token: 'CAACEdEose0cBAEBVPyWZAliTBrPRFXPByF1fqnZBon4vB35HuZC7atCSGmhA3cuZAW0xiqBXMkzZC0wp1yIEaKMLXmZAzboGQo9ZAYBdiTfiQD7SbSJwSOM5sbgYSvGSI3hewDq5mcneewwt7meeDsrb35yFz9bV5crXr8xw9ZCZCRIoB0qKVUnZCNE2LnZB90eDPcZD'
        :foursquare:
            :token: '1498rhfdsflsaj2893rhfefsd'
            :venues:
                - :id: '12345'
                - :id: '45657'

        :twitter:
            :token: '857919337-0UubltaCQLVnjXmRfw0ci648Baw54XmN0UTocHpO'
            :token_secret: 'JbRByo79ZFts44B7G54gLa4Czfd5VCkcMwyOocVwwA'
            :terms:
                - 'canjs'
                - 'stealjs'
                - 'jquery'
                - 'javascript'
        # :github:
        #     :token: 'c27ac77b9951537a008b1ab2ef8dfe0035fac8c8'
        #     :repos:
        #         - 'veljkodragsic/mocker'
        #         - 'veljkodragsic/apes'
        #         - 'bithub-test/refy'
        #     :orgs:
        #         - 'floatingpointio'

        # :meetup:
        #     :token: 'f66dad869e6bd4268258a5fe181068ad'
        #     :terms:
        #         - 'canjs'
        #         - 'jquerypp'
        #     :groups:
        #         - '12asldkgn32'
        #         - '23sdfkvl432'
        #         - '234as23lvf4'

    :nikica:
        :twitter:
            :token: '55592490-2wJvxrMg7YS1Ndf2N0bGe8DRMr2ba3wmukx0vMUHw'
            :token_secret: 'XREakQgM9iXvploScr7jT8JbwFlWapNO3PVrBSbTE'
            :terms:
                - 'meetup'
                - 'ruby'
                - 'rails'
        :facebook:
            :token: 'CAACEdEose0cBANHA5ACsEMZAjdM3E08ap0qQ9MZCYVaqqdRpZBve5MSG7oUUo5ZBCX2x17ZCMs2Gg5KKqd7cGeyNdak45WTcyNuafJKhT3Xf9ADvmrRZAMVuT798BHqIuZCuBRU4Vn1YsOWnIpsrHHYNfkLfToRLP1ZABcxU85KkuVDqNPRsCbR7nOp9Kcnki9IZD'
            :pages:
                - :id: '487939194652299'
                  :token: 'CAACEdEose0cBAPgl4wnuZBdBbT34dBZCKNrurbGdrQth8Oo7dgvzYOVQZBiobCHEUQW82dZAoJJ9ZC9QDtcabMHR34NHNh7DPP6ebVC0dOJpniNLYVbDZCXVk6b7se4VJ1a06CZC9IGw9ynpYPknblZA379kWzOLmB8J5INwTPkejMpKIXKFp46ixgIPWLMPRnFDMy7UudyGYwZDZD'
        :foursquare:
            :token: '_token_for_foursquare_'
            :venues:
                - :id: '45657'
                - :id: '67890'
        # :disqus:
        #     :token: 'b08029df87f74c99afeba385e519e3e0'
        #     :related:
        #         - 'thread'
        #         - 'forum'
        #     :forums:
        #         - 'jmvcs3'
        #         - 'bitovi'
        # :github:
        #     :token: '2d0b3cfc15cf0b6d1cf21dd8004921535b76187e'
        #     :repos:
        #         - 'veljkodragsic/mocker'
        #         - 'veljkodragsic/apes'
        #         - 'bithub-test/refy'
        #     :orgs:
        #         - 'floatingpointio'
