:intervals:
    :github:
        :events: 2000
        :issues:
            :open: 5000
            :closed: 6000
    :disqus: 3000
    :forum: 2000
    :meetup: 4
    :blog: 2000
    :twitter: 5000

:feeds:
    :blog:
        :url: 'http://www.bitovi.com/blog.rss'

    :forum:
        :general:
            :url: 'https://forum.javascriptmvc.com/feed'
        :questions:
            :url: 'https://forum.javascriptmvc.com/feed/filter/questions'

    :disqus:
        :posts:
            :url: 'http://disqus.com/api/3.0/posts/list.json'
            :query:
                :forum:
                    - 'jmvcs3'
                    - 'bitovi'
                :related:
                    - 'thread'
                    - 'forum'
                :api_key: 'NgGGShovTbuUwxX61HNZvHreDse9DXrW8zvqlJOUhn6BVKJFISuYACtjhZ17FFZB'

    :meetup:
        :open_events:
            :polling:
                :url: "https://api.meetup.com/2/open_events"
                :query:
                    :sign: "true"
                    :key: "663a24605a37767831495d6332546b4a"
                    :text: "canjs"
            :streaming:
                :url: "http://stream.meetup.com/2/open_events"


    :github:
        :head:
            :authorization: "token c27ac77b9951537a008b1ab2ef8dfe0035fac8c8"
            :accept: "application/vnd.github.v3+json"
        :repos:
            :testy:
                :events: 'https://api.github.com/repos/bithub-test/testy/events'
                :issues: 'https://api.github.com/repos/bithub-test/testy/issues'

    :twitter:
        :public:
            :streaming:
                :path: '/1.1/statuses/filter.json'
                :params:
                    :track: 'canjs,stealjs,javascriptmvc,jquerypp,documentjs,jquery++'
                :oauth:
                    :consumer_key: "huCmG0TZ7vs6leLqLNlGQ"
                    :consumer_secret: "X4mx1qgGlZ1BVIFFUDB4kzrE1NV7t0nAjx5hY5tQOWQ"
                    :token: "55592490-2wJvxrMg7YS1Ndf2N0bGe8DRMr2ba3wmukx0vMUHw"
                    :token_secret: "XREakQgM9iXvploScr7jT8JbwFlWapNO3PVrBSbTE"
            :polling:
                :url: 'https://api.twitter.com/1.1/search/tweets.json'
                :query:
                    q: 'canjs,stealjs,javascriptmvc,jquerypp,documentjs,jquery++'


        :user_streams:
            :bitovi_bithub:
                :host: 'userstream.twitter.com'
                :method: 'GET'
                :path: '/1.1/user.json'
                :oauth:
                    :consumer_key: "O8LBlzL77IMhcUd58PaCA"
                    :consumer_secret: "GgBnHe2pyNbVQoBiZYMqeRM39juGphZ4tsCcpn79uTM"
                    :token: "1911709506-lxbZcO7DbjeZ4D6HlfpHTmYaMgyNwKyD1x3OcZs"
                    :token_secret: "H4mVLnP21EUD2zkvfonQfIOMS0GVT585bXhRNMT9ZI"
