# :blog:
#     :polling:
#         :posts:
#             :url: 'http://www.bitovi.com/blog.rss'
#             :interval: 1

# :forum:
#     :polling:
#         :general:
#             :url: 'https://forum.javascriptmvc.com/feed'
#             :interval: 1
#         :questions:
#             :url: 'https://forum.javascriptmvc.com/feed/filter/questions'
#             :interval: 1

# :disqus:
#     :data:
#         :auth: &disqus_auth
#             :api_key: 'NgGGShovTbuUwxX61HNZvHreDse9DXrW8zvqlJOUhn6BVKJFISuYACtjhZ17FFZB'
#     :polling:
#         :posts:
#             :url: 'http://disqus.com/api/3.0/posts/list.json'
#             :interval: 1
#             :params:
#                 <<: *disqus_auth
#                 :forum:
#                     - 'jmvcs3'
#                     - 'bitovi'
#                 :related:
#                     - 'thread'
#                     - 'forum'

# :stackexchange:
#     :data:
#         :auth: &stackexchange_auth
#             :access_token: "ai*6QcDJ8qVkQKqxXbUARw))"
#             :key: "8EAiwRhHlupc0Z1aV3SCVg(("
    
#     :polling:
#         :canjs_questions:
#             :interval: 1
#             :url: "https://api.stackexchange.com/2.2/questions"
#             :params:
#                 <<: &stackexchange_auth
#                 :site: "stackoverflow"
#                 :tagged: "canjs"
#                 :filter: "_GZ-2_GIz-dSc9CjKwGP4UEOutlPKHh*F)x8rj8B2kRb1dHxpaJFC5Upazs"
#         :javascriptmvc_questions:
#             :interval: 1
#             :url: "https://api.stackexchange.com/2.2/questions"
#             :params:
#                 <<: &stackexchange_auth
#                 :site: "stackoverflow"
#                 :tagged: "javascriptmvc"
#                 :filter: "_GZ-2_GIz-dSc9CjKwGP4UEOutlPKHh*F)x8rj8B2kRb1dHxpaJFC5Upazs"

:meetup:
    :data:
        :auth: &meetup_auth
            :key: &meetup_api_key "663a24605a37767831495d6332546b4a"
            :sign: "true"
    :polling:
        :open_events:
            :interval: 20
            :api_key: *meetup_api_key
            :params:
                :text: "canjs"
                :fields: "event_hosts"
        :events:
            :interval: 10
            :api_key: *meetup_api_key
            :params:
                :status: "past"
                :fields: "event_hosts"
            :boot_data_url: "http://bithub.dev/api/v2/crawler/event_ids"
        :rsvps:
            :interval: 5
            :api_key: *meetup_api_key
            :boot_data_url: "http://bithub.dev/api/v2/crawler/event_ids"
    :streaming:
        :open_events:
            :url: "http://stream.meetup.com/2/open_events"
        :rsvps:
            :url: "http://stream.meetup.com/2/rsvps"

:github:
    :data:
        :token: &token 'c27ac77b9951537a008b1ab2ef8dfe0035fac8c8'
    :polling:
      :activity:
        :user: 'bithub-test'
        :repo: 'testy'
        :token: *token
        :interval: 2

      :issues:
        :interval: 10
        :user: 'bithub-test'
        :repo: 'testy'
        :token: *token

      :issues_comments:
        :interval: 5
        :user: 'bithub-test'
        :repo: 'testy'
        :token: *token

      :pull_requests:
        :interval: 10
        :user: 'bithub-test'
        :repo: 'testy'
        :token: *token

      :pull_requests_comments:
        :interval: 5
        :user: 'bithub-test'
        :repo: 'testy'
        :token: *token

:twitter:
    :data: 
        :auth: &public_twitter_auth
            :consumer_key: "huCmG0TZ7vs6leLqLNlGQ"
            :consumer_secret: "X4mx1qgGlZ1BVIFFUDB4kzrE1NV7t0nAjx5hY5tQOWQ"
            :token: "55592490-2wJvxrMg7YS1Ndf2N0bGe8DRMr2ba3wmukx0vMUHw"
            :token_secret: "XREakQgM9iXvploScr7jT8JbwFlWapNO3PVrBSbTE"
        :terms: &default_terms
            - 'canjs'
            - 'stealjs'
            - 'javascriptmvc'
            - 'jquerypp'
            - 'documentjs'

    :streaming:
        :public:
            :params:
                :track: *default_terms
            :oauth:
                <<: *public_twitter_auth
        :bitovi_bithub_user:
            :oauth:
                :consumer_key: "O8LBlzL77IMhcUd58PaCA"
                :consumer_secret: "GgBnHe2pyNbVQoBiZYMqeRM39juGphZ4tsCcpn79uTM"
                :token: "1911709506-lxbZcO7DbjeZ4D6HlfpHTmYaMgyNwKyD1x3OcZs"
                :token_secret: "H4mVLnP21EUD2zkvfonQfIOMS0GVT585bXhRNMT9ZI"
    :polling:
        :tweet_search:
            :interval: 60
            :terms: *default_terms
            :oauth:
                <<: *public_twitter_auth
