:intervals:
  :github:
    :events: 30
    :issues:
      :open: 300
      :closed: 3600
  :disqus: 300
  :forum: 120
  :meetup:
    :rsvps: 120
    :all_events: 600
    :events: 300
  :blog: 600
  :twitter: 900

:feeds:
  :blog:
    :url: 'http://www.bitovi.com/blog.rss'

  :forum:
    :general:
      :url: 'https://forum.javascriptmvc.com/feed'
    :questions:
      :url: 'https://forum.javascriptmvc.com/feed/filter/questions'

  :disqus:
    :posts:
      :url: 'http://disqus.com/api/3.0/posts/list.json'
      :query:
        :forum:
          - 'jmvcs3'
          - 'bitovi'
        :related:
          - 'thread'
          - 'forum'
        :api_key: 'NgGGShovTbuUwxX61HNZvHreDse9DXrW8zvqlJOUhn6BVKJFISuYACtjhZ17FFZB'

  :meetup:
    :open_events:
      :polling:
        :url: "https://api.meetup.com/2/open_events"
        :query:
          :sign: "true"
          :key: "663a24605a37767831495d6332546b4a"
          :text: "canjs"
          :fields: "event_hosts"
      :streaming:
        :url: "http://stream.meetup.com/2/open_events"
    :all_events:
      :url: "https://api.meetup.com/2/events"
      :query:
        :sign: "true"
        :key: "663a24605a37767831495d6332546b4a"
        :fields: "event_hosts"
        :status: "past"
      :boot_data_url: "http://bithub.com/api/v2/crawler/event_ids"
    :rsvps:
      :url: "https://api.meetup.com/2/rsvps"
      :query:
        :sign: "true"
        :key: "663a24605a37767831495d6332546b4a"
      :boot_data_url: "http://bithub.com/api/v2/crawler/event_ids"

  :twitter:
    :public:
      :streaming:
        :path: '/1.1/statuses/filter.json'
        :params:
          :track: canjs,stealjs,javascriptmvc,jquerypp,documentjs,jquery++
        :oauth:
          :consumer_key: 'lGtKxbNqkGDfwDr3S8SFEw'
          :consumer_secret: 'dGZa1lO3Aan0tHLUUEtTSxg4Eg0UUcTudkpeU0elHo'
          :token: '123763453-qZStr9dgnjjHVjCHVFKCK0zd7pFSCjx3xC2UWRrf'
          :token_secret: 'hBSs3shmiGvouciTLbjP9FnDNr9S5DOH93gYVCzfY'
      :polling:
        :url: 'https://api.twitter.com/1.1/search/tweets.json'
        :query:
          q: 'canjs,stealjs,javascriptmvc,jquerypp,documentjs,jquery++'

    :user_streams:
      :bitovi:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: 'jXDoGgRvAr9QyiEZoeQOqw'
          :consumer_secret: 'aG8WTlXJxJZFkz8vOnVLxcEqHPSYARqr5AhbKfcJ4A'
          :token: '123763453-Iwec9rg9Je3iAuNHixSbajQrsyHV4DGxqfK3Z362'
          :token_secret: 'WjxCyMXYbe9Dxgiy7YLPqkSRsonJhKU1edvLJsPWAA'

      :canjs:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: 'imczycfZ0kHrziNCWqcldg'
          :consumer_secret: 'VjKT5zRSurZtIYrS9db9kxl8WH0HlUUeEkSVoN8rok'
          :token: '523041627-VVNsxgQwb3IsslTpRuWia3E3KMmq46VlJsYJb5Y0'
          :token_secret: 'W0gdkMuSVvJMcR2Q6jJ6FEjlcXmmtybsyBK4pI'

      :jquerypp:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: 'ntMRzcTggjBJkq48cuyyjA'
          :consumer_secret: 'xksGh6vK0FOzciz72tZmF7IdC3Owe2u8KyUQxbv9BY'
          :token: '589215872-r9IG7UA3jSmlX3AS73mKr7laTkpqtjyZUoswahHO'
          :token_secret: 'XE2h3Kvnvp8G7DAU9DDME4Vatakf5Kmpd0R6q4tL4Z0'

      :javascriptmvc:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: 'XrZkC4arltXkv80MGg'
          :consumer_secret: 'nd96gRSm5lBccKnz6e2NcfID4BozsPPDHWuJsNIp3AY'
          :token: '56956664-Vd6tMMECvDEFAGVm6yj5cJY12UGKebxGFJzyaVwbI'
          :token_secret: '5FiSwZ3MdCYrzDjOZAMVH2hylZtHVnNxDRyaqD8iE'

      :funcunit:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: 'QYo6Pe406pNJlBWqN3Nkg'
          :consumer_secret: 'MLCuiIl4bDNfEMdGvR7DcW7exJtGsIGeAKULXzAez4'
          :token: '171351462-XYaDcD3aZdLStLuBgWHSg22qHPudAVrVLS27SIDb'
          :token_secret: 'PDnZEP6I1OG26x5WKZ5iTSIBu8ESQIfj2ZvWMwrFTaU'

      :stealjs:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: '0sSF9HBX98z7WedK6liA'
          :consumer_secret: 'G8lXrrYWS3B7E9aRSjyl5VFMaSNLVpAKfKkGb6wcTU'
          :token: '1114748720-Oy5Y61k7rsABQtIqZu42uFEfDaprvq4u41H8tZ8'
          :token_secret: 'IGJLpsd5uvRqxuHEVjnIEkY4CzWoot2OhjYdwWsUyk'

  :github:
    :head:
      :authorization: "token c27ac77b9951537a008b1ab2ef8dfe0035fac8c8"
      :accept: "application/vnd.github.v3+json"
    :repos:
      :canjs:
        :events: 'https://api.github.com/repos/bitovi/canjs/events'
        :issues: 'https://api.github.com/repos/bitovi/canjs/issues'
      :steal:
        :events: 'https://api.github.com/repos/bitovi/steal/events'
        :issues: 'https://api.github.com/repos/bitovi/steal/issues'
      :documentjs:
        :events: 'https://api.github.com/repos/bitovi/documentjs/events'
        :issues: 'https://api.github.com/repos/bitovi/documentjs/issues'
      :jquerypp:
        :events: 'https://api.github.com/repos/bitovi/jquerypp/events'
        :issues: 'https://api.github.com/repos/bitovi/jquerypp/issues'
      :canui:
        :events: 'https://api.github.com/repos/bitovi/canui/events'
        :issues: 'https://api.github.com/repos/bitovi/canui/issues'
      :funcunit:
        :events: 'https://api.github.com/repos/bitovi/funcunit/events'
        :issues: 'https://api.github.com/repos/bitovi/funcunit/issues'
      :donejs:
        :events: 'https://api.github.com/repos/bitovi/donejs/events'
        :issues: 'https://api.github.com/repos/bitovi/donejs/issues'
      :javascriptmvc:
        :events: 'https://api.github.com/repos/bitovi/javascriptmvc/events'
        :issues: 'https://api.github.com/repos/bitovi/javascriptmvc/issues'
      :testee:
        :events: 'https://api.github.com/repos/bitovi/testee.js/events'
        :issues: 'https://api.github.com/repos/bitovi/testee.js/issues'
