:public_streams:
    :twitter:
        :api_key: 'L9KJpnqaL0phM3u3NBYf3A'
        :api_secret: 'HHMyYzHRoj9qrHw6gmobQWBpTnLOgxBWBMRA0ICk4U'
    :meetup:
        :api_key: '663a24605a37767831495d6332546b4a'
