- name: Initial setup
  hosts: staging
  user: root
  vars:
    pg:
      version: '9.4'
    ruby:
      version: '2.1.2'
    bithub:
      project_path: '/home/bithub'
    pg_dump:
      path: '/pg_dumps/'
      dbname: 'bithub'
  roles:
    # - { role: jessie            , tags: ['jessie'] }
    # - { role: common            , tags: ['common'] }
    # # - { role: ssh             , tags: ['ssh'] }
    # - { role: nodejs            , tags: ['nodejs'] }
    # - { role: nginx             , tags: ['nginx'] }
    # - { role: postgresql        , tags: ['postgresql'] }
    # - { role: rabbitmq          , tags: ['rabbitmq'] }
    # - { role: redis             , tags: ['redis'] }
    # - { role: hostname          , tags: ['hostname'] }
    # - { role: ruby              , tags: ['ruby'] }
    - { role: bithub_prod       , tags: ['bithub'] }
    # - { role: linode_networking , tags: ['linode_networking'] }
    - { role: pg_dump           , tags: ['pg_dump'] }
