language: ruby
script:
  - "./bin/rake db:migrate"
  - "./bin/rake db:test:prepare"
  - "./bin/rspec spec/domain/wrappers"
  - "./bin/rspec spec/domain/events"
notifications:
  recipients:
    - veljko@kset.org
    - neektza@gmail.com
    - konjevic@gmail.com
addons:
  postgresql: 9.3
  code_climate:
    repo_token: 2142151d5ad5912f06df9c908ae9676d885650166ba091ac999ab82d7c87747f
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database bithub_test;' -U postgres
  - "cp ./.travis_database.yml ./config/database.yml"
