language: ruby
script: "bundle exec rspec"
notifications:
  recipients:
    - veljko@kset.org
    - neektza@gmail.com
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database bithub_test;' -U postgres
