language: ruby
cache: bundler
env:
  - REDIS_URL=redis://127.0.0.1:6379/15 RAILS_ENV=test
script:
  - "bundle exec rake spec:models && bundle exec rake spec:services && bundle exec rake spec:requests"
notifications:
  slack: bitovi:a6EZ5xpLzrpMgCYyvKwfkmN5
services:
  - redis-server
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 2142151d5ad5912f06df9c908ae9676d885650166ba091ac999ab82d7c87747f
  ssh_known_hosts: 45.79.201.206
rvm:
  - 2.2.2
before_script:
  - "cp ./.travis_database.yml ./config/database.yml"
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"
deploy:
  provider: script
  script: ./.travis/deploy.sh
  skip_cleanup: true
  on:
    branch: develop
