- name: Install RabbitMQ
  apt: name={{ item }} state=installed
  with_items:
    - rabbitmq-server
    - amqp-tools
  notify:
    - restart rabbitmq

- name: Enable RabbitMQ management plugin
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify:
    - restart rabbitmq
