module Intervals
  ACTOR_MAILBOX_REPORT = 30
  POLLER_HEARTBEAT = 10
  COMMAND_HANDLER_RETRY = 3

  module Polling
    FACEBOOK_FEED = 3600

    GITHUB_ORG_ACTIVITY = 60
    GITHUB_REPO_ACTIVITY = 60
    GITHUB_REPO_ISSUES = 600
    GITHUB_REPO_PULL_REQUESTS = 600
    GITHUB_REPO_ISSUE_COMMENTS = 300
    GITHUB_REPO_PULL_REQUEST_COMMENTS = 300

    TUMBLR_BLOG = 600
    TUMBLR_TAG = 600

    TWITTER_FOLLOWERS = 600
    TWITTER_HASHTAG = 120
    TWITTER_TERM = 120
    TWITTER_USER_TIMELINE = 60

    YOUTUBE_CHANNEL = 900
    YOUTUBE_PLAYLIST = 900
    YOUTUBE_USER = 900

    DISQUS_FORUM = 60

    MEETUP_GROUP = 3600
    MEETUP_EVENT = 900

    RSS_SITE = 600

    STACKEXCHANGE_QUESTIONS = 1800
    STACKEXCHANGE_SEARCH = 1800
  end
end
