:rabbitmq:
  :host: "127.0.0.1"
  :port: "5672"
  :user: "bithub"
  :pass: "Ei7PhaaH"
  :vhost: "bithub"

:bithub:
  :endpoint: "http://bithub.dev"

:github:
  :repos:
    -
      :name: "bithub-test/testy"
      :uri: "git@github.com:bithub-test/testy.git"
      :local_path: "/tmp/testy"
  :users:
    -
      :access_token: "31d0e90cb5c2154e49e0247d7823aa768ba7c346"
      :username: "bitovi-bithub-test"
      :password: "mX5J378M1BRL"
      :email: "bithub@testing.bithub.com"
