# Some useful aliases for the bash

# Some common shortcuts for file-/directory commands
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias l='ls'
alias grep='grep --color=auto'

# Aliases for common chmods
alias 000='chmod 000'
alias 644='chmod 644'
alias 755='chmod 755'

# Aliases for Debian-based systems
#alias agu='sudo apt-get update'
#alias agg='sudo apt-get upgrade'
#alias agi='sudo apt-get install'
#alias acs='apt-cache search'

# Execute the last command as root
alias lr='sudo $(history | tail -n 2 | head -n 1 | sed -e "s/^[ ]*[0-9]*[ ]*//g")'

# Search for a process containing a given name
function pps() {
	ps aux | grep "$@" | grep -v 'grep';
}
