log4r_config:
  loggers:
    - name          : component
      level         : DEBUG
      trace         : 'true'
      outputters    :
        - component_logfile
        - console

    - name          : rails
      level         : DEBUG
      trace         : 'false'
      outputters    :
        - rails_logfile
        - console
    
    - name          : active_record
      level         : DEBUG
      trace         : 'false'
      outputters    :
        - active_record_logfile

  outputters:
    - name      : console
      type      : StdoutOutputter
      formatter :
        type    : PatternFormatter
        pattern : '%m'

    - name      : component_logfile
      type      : FileOutputter
      filename  : "log/#{ENV}_#{COMPONENT_NAME}.log"
      trunc     : true
      maxsize   : 104857600
      formatter :
        type    : PatternFormatter
        pattern : '[%d]: %m'
    
    - name      : active_record_logfile
      type      : FileOutputter
      filename  : "log/#{ENV}_active_record.log"
      trunc     : true
      maxsize   : 104857600
      formatter :
        type    : PatternFormatter
        pattern : '[%d]: %m'

    - name      : rails_logfile
      type      : FileOutputter
      filename  : "log/#{ENV}.log"
      trunc     : true
      maxsize   : 104857600
      formatter :
        type    : PatternFormatter
        pattern : '[%d]: %m'
