log4r_config:
  loggers:
    - name          : component
      level         : INFO
      trace         : 'true'
      outputters    :
        - component_logfile
        - console

    - name          : active_record
      level         : INFO
      trace         : 'false'
      outputters    :
        - active_record_logfile

    - name          : action_controller
      level         : INFO
      trace         : 'false'
      outputters    :
        - action_controller_logfile

  outputters:
    - name      : console
      type      : StdoutOutputter
      formatter :
        type: PatternFormatter
        pattern: '[%l]: %m '

    - name     : component_logfile
      type     : DateFileOutputter
      dirname  : "/home/bithub/web/shared/log"
      filename : "#{COMPONENT_NAME}.log"
      trunc    : false
      maxsize  : 104857600
      max_backups : 10
      formatter:
        type: PatternFormatter
        pattern: '[%d][%l]: %m '

    - name     : active_record_logfile
      type     : DateFileOutputter
      dirname  : "/home/bithub/web/shared/log"
      filename : "active_record.log"
      trunc    : false
      maxsize  : 104857600
      max_backups : 10
      formatter:
        type: PatternFormatter
        pattern: '[%d][%l]: %m '

    - name     : action_controller_logfile
      type     : DateFileOutputter
      dirname  : "/home/bithub/web/shared/log"
      filename : "action_controller.log"
      trunc    : false
      maxsize  : 104857600
      max_backups : 10
      formatter:
        type: PatternFormatter
        pattern: '[%d][%l]: %m '
