log4r_config:
  loggers:
    - name          : component
      level         : INFO
      trace         : 'true'
      outputters    :
        - component_logfile

    - name          : active_record
      level         : INFO
      trace         : 'false'
      outputters    :
        - active_record_logfile

    - name          : action_controller
      level         : INFO
      trace         : 'false'
      outputters    :
        - action_controller_logfile

  outputters:
    - name     : component_logfile
      type     : DateFileOutputter
      filename : "/var/log/bithub/#{COMPONENT_NAME}.log"
      trunc    : false
      maxsize  : 104857600
      formatter:
        type: PatternFormatter
        pattern: '[#{ENV}][%d][%l]: %m '

    - name     : active_record_logfile
      type     : DateFileOutputter
      dirname  : "/var/log/bithub"
      filename : "active_record.log"
      formatter:
        type: PatternFormatter
        pattern: '[%d][%l]: %m '

    - name     : action_controller_logfile
      type     : DateFileOutputter
      dirname  : "/var/log/bithub"
      filename : "action_controller.log"
      formatter:
        type: PatternFormatter
        pattern: '[%d][%l]: %m '
