digest:
  follow: 10 # follow_event
  fork: 10   # fork_event
  watch: 10  # watch_event

twitter:
  tweet: 10 # status_event

comment:
  disqus: 10
  commit_comment: 10 # commit_comment_event
  issue_comment: 10 # issue_comment_event
  pull_request_review_comment: 10 # pull_request_review_comment_event

code:
  commit: 10
  push: 10 # push_event
  create_event: 10
  delete_event: 10
  pull_request: 10 # pull_request_event

question:
  forum: 10
  question: 10

chat:
  irc: 10

article:
  blog: 10

issue:
  issue: 10 # issues_event

bug:
  issue: 10 # issues_event
  bug: 5

feature:
  issue: 10 # issues_event
  feature: 5
  feature_request: 5
  enhancement: 5
