digest:
  follow_event: 10
  fork_event: 10
  watch_event: 10

twitter:
  status_event: 10

comment:
  disqus: 10

github_comment:
  commit_comment_event: 10
  issue_comment_event: 10
  pull_request_review_comment_event: 10

code:
  push_event: 10
  create_event: 10
  delete_event: 10
  pull_request_event: 10

question:
  forums: 10
  question: 10

chat:
  irc: 10

article:
  blog: 10

issue:
  issues_event: 10

bug:
  issues_event: 10
  bug: 5

feature:
  issues_event: 10
  feature: 5
  feature_request: 5
  enhancement: 5
