:intervals:
  :github:
    :events: 30
    :issues:
      :open: 300
      :closed: 3600
  :disqus: 30
  :forums: 120
  :blog: 600

:feeds:
  :blog: 'http://www.bitovi.com/blog.rss'

  :forums:
    :general: 'https://forum.javascriptmvc.com/feed'
    :terms:
      :questions: 'https://forum.javascriptmvc.com/feed/filter/questions'

  :disqus:
    :uri: 'http://disqus.com/api/3.0/posts/list.json'
    :query:
      :forum:
        - 'jmvcs3'
        - 'bitovi'
      :related:
        - 'thread'
        - 'forum'
    :api_key: 'NgGGShovTbuUwxX61HNZvHreDse9DXrW8zvqlJOUhn6BVKJFISuYACtjhZ17FFZB'

  :twitter:
    :streams:
      :public_feed:
        :path: '/1.1/statuses/filter.json'
        :params:
          :track: canjs,stealjs,javascriptmvc,jquerypp,documentjs,jquery++
        :oauth:
          :consumer_key: 'lGtKxbNqkGDfwDr3S8SFEw'
          :consumer_secret: 'dGZa1lO3Aan0tHLUUEtTSxg4Eg0UUcTudkpeU0elHo'
          :token: '123763453-qZStr9dgnjjHVjCHVFKCK0zd7pFSCjx3xC2UWRrf'
          :token_secret: 'hBSs3shmiGvouciTLbjP9FnDNr9S5DOH93gYVCzfY'

      :user_feeds:
        :bitovi:
          :host: userstream.twitter.com
          :method: GET
          :path: /1.1/user.json
          :oauth:
            :consumer_key: 'jXDoGgRvAr9QyiEZoeQOqw'
            :consumer_secret: 'aG8WTlXJxJZFkz8vOnVLxcEqHPSYARqr5AhbKfcJ4A'
            :token: '123763453-Iwec9rg9Je3iAuNHixSbajQrsyHV4DGxqfK3Z362'
            :token_secret: 'WjxCyMXYbe9Dxgiy7YLPqkSRsonJhKU1edvLJsPWAA'

        :canjs:
          :host: userstream.twitter.com
          :method: GET
          :path: /1.1/user.json
          :oauth:
            :consumer_key: 'imczycfZ0kHrziNCWqcldg'
            :consumer_secret: 'VjKT5zRSurZtIYrS9db9kxl8WH0HlUUeEkSVoN8rok'
            :token: '523041627-VVNsxgQwb3IsslTpRuWia3E3KMmq46VlJsYJb5Y0'
            :token_secret: 'W0gdkMuSVvJMcR2Q6jJ6FEjlcXmmtybsyBK4pI'

        :jquerypp:
          :host: userstream.twitter.com
          :method: GET
          :path: /1.1/user.json
          :oauth:
            :consumer_key: 'ntMRzcTggjBJkq48cuyyjA'
            :consumer_secret: 'xksGh6vK0FOzciz72tZmF7IdC3Owe2u8KyUQxbv9BY'
            :token: '589215872-r9IG7UA3jSmlX3AS73mKr7laTkpqtjyZUoswahHO'
            :token_secret: 'XE2h3Kvnvp8G7DAU9DDME4Vatakf5Kmpd0R6q4tL4Z0'

        :javascriptmvc:
          :host: userstream.twitter.com
          :method: GET
          :path: /1.1/user.json
          :oauth:
            :consumer_key: 'XrZkC4arltXkv80MGg'
            :consumer_secret: 'nd96gRSm5lBccKnz6e2NcfID4BozsPPDHWuJsNIp3AY'
            :token: '56956664-Vd6tMMECvDEFAGVm6yj5cJY12UGKebxGFJzyaVwbI'
            :token_secret: '5FiSwZ3MdCYrzDjOZAMVH2hylZtHVnNxDRyaqD8iE'

        :funcunit:
          :host: userstream.twitter.com
          :method: GET
          :path: /1.1/user.json
          :oauth:
            :consumer_key: 'QYo6Pe406pNJlBWqN3Nkg'
            :consumer_secret: 'MLCuiIl4bDNfEMdGvR7DcW7exJtGsIGeAKULXzAez4'
            :token: '171351462-XYaDcD3aZdLStLuBgWHSg22qHPudAVrVLS27SIDb'
            :token_secret: 'PDnZEP6I1OG26x5WKZ5iTSIBu8ESQIfj2ZvWMwrFTaU'

        :stealjs:
          :host: userstream.twitter.com
          :method: GET
          :path: /1.1/user.json
          :oauth:
            :consumer_key: '0sSF9HBX98z7WedK6liA'
            :consumer_secret: 'G8lXrrYWS3B7E9aRSjyl5VFMaSNLVpAKfKkGb6wcTU'
            :token: '1114748720-Oy5Y61k7rsABQtIqZu42uFEfDaprvq4u41H8tZ8'
            :token_secret: 'IGJLpsd5uvRqxuHEVjnIEkY4CzWoot2OhjYdwWsUyk'

  :github:
    :token: c27ac77b9951537a008b1ab2ef8dfe0035fac8c8
    :repos:
      :canjs:
        :events: 'https://api.github.com/repos/bitovi/canjs/events'
        :issues: 'https://api.github.com/repos/bitovi/canjs/issues'
      :steal:
        :events: 'https://api.github.com/repos/bitovi/steal/events'
        :issues: 'https://api.github.com/repos/bitovi/steal/issues'
      :documentjs:
        :events: 'https://api.github.com/repos/bitovi/documentjs/events'
        :issues: 'https://api.github.com/repos/bitovi/documentjs/issues'
      :jquerypp:
        :events: 'https://api.github.com/repos/bitovi/jquerypp/events'
        :issues: 'https://api.github.com/repos/bitovi/jquerypp/issues'
      :canui:
        :events: 'https://api.github.com/repos/bitovi/canui/events'
        :issues: 'https://api.github.com/repos/bitovi/canui/issues'
      :funcunit:
        :events: 'https://api.github.com/repos/bitovi/funcunit/events'
        :issues: 'https://api.github.com/repos/bitovi/funcunit/issues'
      :javascriptmvc:
        :events: 'https://api.github.com/repos/bitovi/javascriptmvc/events'
        :issues: 'https://api.github.com/repos/bitovi/javascriptmvc/issues'
      :testee:
        :events: 'https://api.github.com/repos/bitovi/testee.js/events'
        :issues: 'https://api.github.com/repos/bitovi/testee.js/issues'
