development:
  adapter: postgresql
  encoding: utf8
  database: bithub_development
  username: bithub
  password: negativ1Q

test:
  adapter: postgresql
  encoding: unicode
  database: bithub_test
  username: bithub
  password: negativ1Q

testing:
  adapter: postgresql
  encoding: unicode
  database: bithub_testing
  pool: 5
  username: bithub
  password: Oof4laed
  socket: /var/run/postgresql/.s.PGSQL.5432

staging:
  adapter: postgresql
  encoding: unicode
  database: bithub_staging
  pool: 5
  username: bithub
  password: Ahc5eish
  socket: /var/run/postgresql/.s.PGSQL.5432

production:
  adapter: postgresql
  encoding: unicode
  database: bithub
  pool: 5
  username: bithub
  password: Chooth5z
  socket: /var/run/postgresql/.s.PGSQL.5432
