development:
  adapter: postgresql
  encoding: unicode
  database: bithub_development
  pool: 5
  username: bithub
  password: negativ1Q
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: bithub_test
  pool: 5
  username: bithub
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bithub_production
  pool: 5
  username: bithub
  password:
