:disqus:
  :api_key: 'NgGGShovTbuUwxX61HNZvHreDse9DXrW8zvqlJOUhn6BVKJFISuYACtjhZ17FFZB'

:twitter:
  :streams:
    :public_feed:
      :path: '/1.1/statuses/filter.json'
      :params:
        :track: canjs,donejs,stealjs,javascriptmvc,jquerypp,documentjs,jquery++
      :oauth:
        :consumer_key: "lbsM6gbXpcTi31rnlrQggw"
        :consumer_secret: "BM1JX3hKq9Y7f5qQbMwWHjbzzwti0a7UajVkjQRKNY"
        :token: "123763453-nweDBSbMJ9p03RGQlUqU1ogBhnEd76S5186h7dEM"
        :token_secret: "u8AMR188VFsi4962zKqCioBb7B8XOTvUt9YlJ8X2fk"

    :user_feeds:
      :bitovi:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "rW6WJoSshiwJ7J02IAfvyg"
          :consumer_secret: "7wIx8cjqSF32BcI7d8KyqxbzqgzzaVhTy7RnYSIyo"
          :token: "123763453-kit6uWMUAgipLjiMvVYQ31LHT7oTWchfsHasJhQM"
          :token_secret: "ju6uFjnrBGHnvAZap9I7XEzHoNCR619dXzPMasucw"

      :canjs:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "3nueOaygH2MbFiDxmJBKg"
          :consumer_secret: "gfCxze390cr2cbsFOB8lU6N0sGr6MUw3OVPfKkg0"
          :token: "523041627-lvoTIaavOAg5iLdnpHcIJgsmwL0sh8yBe2v0NSHR"
          :token_secret: "Q9vxRs2e2QQ6QHN0tBgjVQl1S0PFGYC11ggBK01muGU"

      :jquerypp:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "JfKIWZNvrFLAxo0SmFZw"
          :consumer_secret: "ANEW03fFCpTeU7Ho4zdWUtQEifriUNugwmk4qose8"
          :token: "589215872-CAmTOTEcEx7Dsu5DRedzeXjvqIachAIeBj6DUyfQ"
          :token_secret: "w8zuEY1FN22W1BqH7mx8tX9kl6MWaw13jrILUmGZw"

      :donejs:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "HsSUG2H64e8Dl9SvUM1Fzg"
          :consumer_secret: "wAgHifIE7Lj7ObiMfW7BrpVYyfcG3zr6EEiMUsxJss"
          :token: "184072309-tRvh9NRDVWLrGkjkrnuKuhjvYoVqzO1WR5IwwZBl"
          :token_secret: "HJVr9bVMRFJgJBCanSxu4PBoAunioLYRTFEnDgP5c5c"

      :javascriptmvc:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "bdwLROP9XbYILeGfT9NQw"
          :consumer_secret: "mvaIHce149XXgF3FBgUzD9BL4IKrz6SwwESjDvcqow"
          :token: "56956664-rXgWbiGz0FAb6TlBlNO5l62eZFwieAV896tdhwGik"
          :token_secret: "Exh6GMwlzA45Ti4lSUNxCupd6hNFigjL65JiKrfB9x8"

      :funcunit:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "ZaefQbfF8L7bUBOuLVCLA"
          :consumer_secret: "XTanJ2prmLm4tqKWYi75UWap0luDxLrYEvY91AinA"
          :token: "171351462-PR34EGUPXkxaLJjBK3mrpGLtmCZuI57VbpMBZiBp"
          :token_secret: "v3A0F6BSgVFz5Mq3rqXgtrzYfSZMFfyRUr3oFo50w"

      :shouldjs:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "1sP7Q2TfLldp1n5sDWfA"
          :consumer_secret: "iXTOsHqRSJA3Kty9NIS0J7rNc41hT44obbyGVMkh8"
          :token: "1114713660-MgeRPj7I5MtZst0VbXkbkjiejJN0npMO1cyBw8B"
          :token_secret: "l1X0FVzp4I5kqCxGSsbFlj3uf0O4PxoCJEb4APGJA"

      :stealjs:
        :host: userstream.twitter.com
        :method: GET
        :path: /1.1/user.json
        :oauth:
          :consumer_key: "TUx7XyHVAIkcavz9vvMDQ"
          :consumer_secret: "UxtDYmYTyCuA8XGQSsehMS4D3OCWiOUEB9DVekRI"
          :token: "1114748720-JKApGwUV3rF6MIPWqjstlIXS5lgLIk605CMmh2x"
          :token_secret: "mmVBTy67ItduK6kaoSqyrk8tfVQH6laeBBvJyN4A"

:github:
  :token: c27ac77b9951537a008b1ab2ef8dfe0035fac8c8
  :repos:
    :testy:
      :events: 'https://api.github.com/repos/bithub-test/testy/events'
      :issues: 'https://api.github.com/repos/bithub-test/testy/issues'
    :canjs:
      :events: 'https://api.github.com/repos/bitovi/canjs/events'
      :issues: 'https://api.github.com/repos/bitovi/canjs/issues'
    :steal:
      :events: 'https://api.github.com/repos/bitovi/steal/events'
      :issues: 'https://api.github.com/repos/bitovi/steal/issues'
    :documentjs:
      :events: 'https://api.github.com/repos/bitovi/documentjs/events'
      :issues: 'https://api.github.com/repos/bitovi/documentjs/issues'
    :jquerypp:
      :events: 'https://api.github.com/repos/bitovi/jquerypp/events'
      :issues: 'https://api.github.com/repos/bitovi/jquerypp/issues'
    :canui:
      :events: 'https://api.github.com/repos/bitovi/canui/events'
      :issues: 'https://api.github.com/repos/bitovi/canui/issues'
    :funcunit:
      :events: 'https://api.github.com/repos/bitovi/funcunit/events'
      :issues: 'https://api.github.com/repos/bitovi/funcunit/issues'
    :donejs:
      :events: 'https://api.github.com/repos/bitovi/donejs/events'
      :issues: 'https://api.github.com/repos/bitovi/donejs/issues'
    :javascriptmvc:
      :events: 'https://api.github.com/repos/bitovi/javascriptmvc/events'
      :issues: 'https://api.github.com/repos/bitovi/javascriptmvc/issues'
