log4r_config:
  # define all loggers:
  loggers:
    - name          : rails
      level         : DEBUG
      trace         : 'false'
      outputters    : 
      - console
      - logfile
    - name          : active_record
      level         : DEBUG
      trace         : 'false'
      outputters    : 
      - console
      - logfile
    - name          : action_controller
      level         : DEBUG
      trace         : 'false'
      outputters    : 
      - console
      - logfile
    - name          : crawler
      level         : DEBUG
      trace         : 'false'
      outputters    : 
      - console
      - logfile
    - name          : listener
      level         : DEBUG
      trace         : 'false'
      outputters    : 
      - console
      - logfile
    - name          : irc_bot
      level         : DEBUG
      trace         : 'false'
      outputters    : 
      - console
      - logfile


 
  # define all outputters (incl. formatters)
  outputters:
  - type: StdoutOutputter
    name: console
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m'
      type        : PatternFormatter
  - type: RollingFileOutputter
    name: logfile
    filename: "/var/log/bithub/#{COMPONENT_NAME}.log"
    trunc: false
    maxsize: 104857600
    formatter:
      pattern     : '[#{MACHINE_NAME}][%p][#{COMPONENT_NAME}]|[RAILS][%d][%l]: %m '
      type        : PatternFormatter

