log4r_config:
  loggers:
    - name          : component
      level         : DEBUG
      trace         : 'true'
      outputters    : 
        - console
        - component_logfile

    - name          : active_record
      level         : DEBUG
      trace         : 'false'
      outputters    : 
        - active_record_logfile

    - name          : action_controller
      level         : DEBUG
      trace         : 'false'
      outputters    : 
        - action_controller_logfile

  outputters:
    - name      : console
      type      : StdoutOutputter
      formatter :
        type: PatternFormatter
        pattern: '[#{COMPONENT_NAME}]|[%d][%l]: %m '

    - name     : component_logfile
      type     : RollingFileOutputter
      filename : "log/#{COMPONENT_NAME}.log"
      trunc    : false
      maxsize  : 104857600
      formatter:
        type: PatternFormatter
        pattern: '[#{ENV}][%d][%l]: %m '

    - name     : active_record_logfile
      type     : DateFileOutputter
      dirname  : "log"
      filename : "active_record.log"
      formatter:
        type: PatternFormatter
        pattern: '[%d][%l]: %m '

    - name     : action_controller_logfile
      type     : DateFileOutputter
      dirname  : "log"
      filename : "action_controller.log"
      formatter:
        type: PatternFormatter
        pattern: '[%d][%l]: %m '
