input {
	file {
		path => [
			"/Users/neektza/projects/bitovi/bithub/log/development_crawler_listener.log",
			"/Users/neektza/projects/bitovi/bithub/log/development_crawler_poller.log",
			"/Users/neektza/projects/bitovi/bithub/log/development_listener.log",
			"/Users/neektza/projects/bitovi/bithub/log/development_rails.log"
		]
	}
}

filter {

	grok {
		match => { 
			"message" => [
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: method=%{WORD:http_method} path=%{UNIXPATH:path} format=%{DATA:req_format} controller=%{DATA:controller_path} action=%{WORD:controller_action} status=%{NUMBER:http_status} duration=%{NUMBER:duration_total} view=%{NUMBER:duration_view} db=%{NUMBER:duration_db}",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\]\[%{WORD:handler_class}\] Mailbox size %{NUMBER:mailbox_size}",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\]\[%{WORD:pipeline}\]%{SPACE}%{WORD:function}%{DATA}%{NUMBER:user_time}%{SPACE}%{NUMBER:system_time}%{SPACE}%{NUMBER:sum_time}%{DATA}\(%{SPACE}%{NUMBER:real_time}\)",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\]\[%{WORD:pipeline}\]%{DATA}%{WORD:feed}/%{WORD:type}%{DATA}%{SPACE}%{NUMBER:user_time}%{SPACE}%{NUMBER:system_time}%{SPACE}%{NUMBER:sum_time}%{DATA}\(%{SPACE}%{NUMBER:real_time}\)",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\] Mailbox size %{NUMBER:mailbox_size}",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\]\[%{NUMBER:brand_id},%{NUMBER:embed_id},%{NUMBER:service_id},%{WORD:feed_name},%{WORD:type_name}\]%{DATA}%{NUMBER:events_published}%{DATA}%{NUMBER:events_fetched}",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\] Fetching %{WORD:feed_name}\/%{WORD:type_name}",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\]\[%{NUMBER:brand_id},%{NUMBER:embed_id},%{NUMBER:service_id},%{WORD:feed_name},%{WORD:type_name}\] %{GREEDYDATA:message}",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: \[%{WORD:component}\] %{GREEDYDATA:message}",
				"\[%{TIMESTAMP_ISO8601:origin_ts}\]\[%{LOGLEVEL:loglevel}\]\: %{GREEDYDATA:message}" 
			]
		}
	}


	mutate {
		convert => { "brand_id" => "integer" }
		convert => { "embed_id" => "integer" }
		convert => { "service_id" => "integer" }
		convert => { "mailbox_size" => "integer" }
		convert => { "events_published" => "integer" }
		convert => { "events_fetched" => "integer" }
		convert => { "duration_total" => "float" }
		convert => { "duration_db" => "float" }
		convert => { "duration_view" => "float" }
	}

}

output {
	stdout { codec => rubydebug }
	elasticsearch_http {
		host => "localhost"
		port => "9200"
	}
}
