
:digest:
  :github: 1
  :twitter: 1
  :follow_event: 1
  :fork_event: 1
  :watch_event: 1

:twitter:
  :twitter: 1
  :status_event: 1

:comment:
  :disqus: 1
  :github: 1
  :commit_comment_event: 1
  :issue_comment_event: 1
  :pull_request_review_comment_event: 1

:code:
  :github: 1
  :push_event: 1
  :create_event: 1
  :delete_event: 1
  :pull_request_event: 1

:feature:
  :github: 1
  :feature: 1
  :feature-request: 1
  :enhancement: 1

:question:
  :github: 1
  :forums: 1
  :question: 1

:chat:
  :irc: 1

:article:
  :blog: 1

:bug:
  github: 1
  bug: 1

