-
  name: 'Default'
  required_tags: {}
  authorship_value: 0
  award_value: 0
  upvote_value: 1

### Twitter

-
  name: 'Posting a Tweet'
  required_tags:
    - twitter
    - tweet

-
  name: 'Follow'
  required_tags:
    - twitter
    - follow

### Github

-
  name: 'Making a push'
  required_tags:
    - github
    - push

-
  name: 'Commiting'
  required_tags:
    - github
    - commit

-
  name: 'Forking a repo'
  required_tags:
    - github
    - fork

-
  name: 'Making pull request'
  required_tags:
    - github
    - pull_request

-
  name: 'Create event'
  required_tags:
    - github
    - create

-
  name: 'Raising an issue'
  required_tags:
    - github
    - issue

-
  name: 'Raising an bug issue'
  required_tags:
    - github
    - issue
    - bug

-
  name: 'Raising an feature issue'
  required_tags:
    - github
    - issue
    - feature

-
  name: 'Closing an issue'
  required_tags:
    - github
    - issue_action
    - closed

### merging pull request ?

-
  name: 'Commeting an issue'
  required_tags:
    - github
    - issue_comment

-
  name: 'Commeting a commit'
  required_tags:
    - github
    - commit_comment

-
  name: 'Starring a repo'
  required_tags:
    - github
    - watch

-
  name: 'Github pull request review comment'
  required_tags:
    - github
    - push

-
  name: 'Github public'
  required_tags:
    - github
    - public

### Forum

### Meetup

-
  name: 'RSVP'
  required_tags:
    - meetup
    - rsvp

# hosting, confirmed, waitlist ... ?

### StackExchange

-
  name: 'Asking question'
  required_tags:
    - stackexchange
    - question

-
  name: 'Answering a question'
  required_tags:
    - stackexchange
    - answer

-
  name: 'Commeting question or answer'
  required_tags:
    - stackexchange
    - comment

### Facebook

-
  name: 'Posting a status'
  required_tags:
    - facebook
    - status

-
  name: 'Like'
  required_tags:
    - facebook
    - like

-
  name: 'Commenting'
  required_tags:
    - facebook
    - comment

-
  name: 'Check-in'
  required_tags:
    - facebook
    - checkin

### Foursquare

-
  name: 'Check-in'
  required_tags:
    - foursquare
    - checkin

-
  name: 'Like'
  required_tags:
    - foursquare
    - like

-
  name: 'Leaving a tip'
  required_tags:
    - foursquare
    - tip

### IRC

-
  name: 'Message'
  required_tags:
    - irc
    - message


# -
#   required_tags:
#     - article
#   authorship_value: 2
#   award_value: 0
#   upvote_value: 1
#   name: 'Submitting an article'

# -
#   required_tags:
#     - twitter
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 1
#   name: 'Tweeting'

# -
#   required_tags:
#     - plugin
#   authorship_value: 2
#   award_value: 0
#   upvote_value: 1
#   name: 'Submitting a plugin'

# -
#   required_tags:
#     - example
#   authorship_value: 0
#   award_value: 0
#   upvote_value: 1
#   name: 'Submitting an example'

# -
#   required_tags:
#     - bug
#     - github
#   authorship_value: 2
#   award_value: 0
#   upvote_value: 1
#   name: 'Reporting a bug'

# -
#   required_tags:
#     - feature
#     - github
#   authorship_value: 2
#   award_value: 0
#   upvote_value: 1
#   name: 'Submitting a feature'

# -
#   required_tags:
#     - app
#   authorship_value: 2
#   award_value: 0
#   upvote_value: 1
#   name: 'Submitting an app'

# -
#   required_tags:
#     - code
#     - github
#   authorship_value: 0
#   award_value: 0
#   upvote_value: 1
#   name: 'Pushing the code'

# -
#   required_tags:
#     - comment
#     - disqus
#   authorship_value: 0
#   award_value: 0
#   upvote_value: 1
#   name: 'Commenting'

# -
#   required_tags:
#     - issue_comment
#     - bug
#     - github
#   authorship_value: 0
#   award_value: 0
#   upvote_value: 1
#   name: 'Submitting a bug'

# -
#   required_tags:
#     - fork
#     - digest
#     - github
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 1
#   name: 'Forking a repo'

# -
#   required_tags:
#     - watch
#     - digest
#     - github
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 1
#   name: 'Starring a repo'

# -
#   required_tags:
#     - follow
#     - twitter
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 1
#   name: 'Following'

# -
#   required_tags:
#     - event
#   authorship_value: 2
#   award_value: 0
#   upvote_value: 1
#   name: 'Organizing an event'

# -
#   required_tags:
#     - rsvp
#     - confirmed
#     - meetup
#   authorship_value: 2
#   award_value: 0
#   upvote_value: 0
#   name: 'Going to the event'

# -
#   required_tags:
#     - rsvp
#     - waitlist
#     - meetup
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 0
#   name: 'RSVPing for an event'

# -
#   required_tags:
#     - stackexchange
#     - question
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 0
#   name: 'Asking a question'

# -
#   required_tags:
#     - stackexchange
#     - comment
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 0
#   name: 'Commenting a question or answer'

# -
#   required_tags:
#     - stackexchange
#     - answer
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 0
#   name: 'Answering a question'

# -
#   required_tags:
#     - foursquare
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 0
#   name: 'Checking in'

# -
#   required_tags:
#     - facebook
#     - like
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 0
#   name: 'Liking a page'

# -
#   required_tags:
#     - facebook
#     - comment
#   authorship_value: 1
#   award_value: 0
#   upvote_value: 0
#   name: 'Commenting on a page'
