-
  required_tags: []
  authorship_value: 0
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - article
  authorship_value: 2
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - twitter
  authorship_value: 1
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - plugin
  authorship_value: 2
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - example
  authorship_value: 0
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - bug
  authorship_value: 2
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - feature
  authorship_value: 2
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - app
  authorship_value: 2
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - code
  authorship_value: 0
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - comment
  authorship_value: 0
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - issue_comment_event
    - bug
  authorship_value: 0
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - fork_event
    - digest
  authorship_value: 1
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - watch_event
    - digest
  authorship_value: 1
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - follow_event
    - twitter
  authorship_value: 1
  award_value: 0
  upvote_value: 1

-
  required_tags:
    - event
  authorship_value: 2
  award_value: 0
  upvote_value: 1
