:feed:
  - github
  - twitter
  - disqus
  - irc
  - forums
  - community_site

:project:
  - javascriptmvc
  - canjs
  - jquerypp
  - stealjs
  - funcunit
  - documentjs
  - testee

:category:
  - bug
  - twitter
  - feature
  - question
  - plugin
  - article
  - app
  - chat
  - code
  - comment
  - event

:label:
  - feature
  - bug
