# --------
# Projects
# --------

canjs:
  display_name: "CanJS"
  group_list: "projects, req_favourites, req_friends"
  aliases:
    - "can_js"

canui:
  display_name: "CanUI"
  group_list: "projects"

javascriptmvc:
  display_name: "JavascriptMVC"
  group_list: "projects, req_favourites, req_friends"
  aliases:
    - "jmvc"
    - "java_script_mvc"

stealjs:
  display_name: "StealJS"
  group_list: "projects, req_friends"
  aliases:
    - "steal"
    - "steal_js"

funcunit:
  display_name: "FuncUnit"
  group_list: "projects, req_favourites, req_friends"
  aliases:
    - "func_unit"

jquerypp:
  display_name: "jQuery++"
  group_list: "projects, req_favourites, req_friends"
  aliases:
    - "j_querypp"
    - "jquery++"
    - "j_query++"

documentjs:
  display_name: "DocumentJS"
  group_list: "projects, req_favourites, req_friends"
  aliases:
    - "document_js"

testee:
  display_name: "Testee.js"
  group_list: "projects, req_friends"
  props:
    levenshtein_treshold: "0"
  aliases:
    - "testeejs"
    - "testee_js"
    - "testee.js"

# --------
# Feeds
# --------

twitter:
  display_name: "Twitter"
  group_list: "feeds, categories"
  props:
    order_on_page: "02"

github:
  display_name: "Github"
  group_list: "feeds"

forum:
  display_name: "Forum"
  group_list: "feeds"

irc:
  display_name: "IRC"
  group_list: "feeds"

blog:
  display_name: "Blog"
  group_list: "feeds"

disqus:
  display_name: "Disqus"
  group_list: "feeds"

bithub:
  display_name: "Bithub"
  group_list: "feeds"
  props:
    levenshtein_treshold: "0"

meetup:
  display_name: "Meetup"
  group_list: "feeds"


# ----------
# Categories
# ----------

app:
  display_name: "App"
  group_list: "categories"
  props:
    order_on_page: "09"
    priority: "100"

article:
  display_name: "Article"
  group_list: "categories"
  props:
    order_on_page: "07"
    priority: "99"

bug:
  display_name: "Bug"
  group_list: "categories, labels"
  props:
    order_on_page: "03"

chat:
  display_name: "Chat"
  group_list: "categories"
  props:
    order_on_page: "99"

code:
  display_name: "Code"
  group_list: "categories"
  props:
    order_on_page: "10"

comment:
  display_name: "Comment"
  group_list: "categories"
  props:
    order_on_page: "04"

github_comment:
  display_name: "Github Comment"
  group_list: "categories"

github_comment:
  display_name: "Github Comment"
  group_list: "categories"

digest:
  display_name: "Digest"
  group_list: "categories"
  props:
    order_on_page: "01"

event:
  display_name: "Event"
  group_list: "categories"
  props:
    order_on_page: "11"

feature:
  display_name: "Feature"
  group_list: "categories, labels"
  aliases:
    - "enhancement"
    - "feature-request"
  props:
    order_on_page: "05"
    priority: "99"

issue:
  display_name: "Issue"
  group_list: "categories"

plugin:
  group_list: "categories"
  display_name: "Plugin"
  props:
    order_on_page: "08"

question:
  group_list: "categories"
  display_name: "Question"
  props:
    order_on_page: "06"


### Twitter specific

tweet: {}

follow: {}

### Github specific

push: {}

commit: {}

fork: {}

pull_request: {}

create_event: {}

issue: {}

issue_comment: {}

issue_action: {}

commit_comment: {}

watch: {}

gollum_event: {}

pull_request_review_comment: {}

commit: {}

public: {}

create: {}

# issues states

open: {}

closed: {}

### Forum specific

post: {}

### Meetup specific

rsvp: {}

### IRC specific

message: {}

### Others

bitovi:
  display_name: "Bitovi"
  group_list: "req_friends"

uncategorized: {}
