# ----------
# Categories
# ----------

article:
  display_name: "Article"
  group_list: "categories"

bug:
  display_name: "Bug"
  group_list: "categories, labels"

chat:
  display_name: "Chat"
  group_list: "categories"

code:
  display_name: "Code"
  group_list: "categories"

comment:
  display_name: "Comment"
  group_list: "categories"

github_comment:
  display_name: "Github Comment"
  group_list: "categories"

digest:
  display_name: "Digest"
  group_list: "categories"

event:
  display_name: "Event"
  group_list: "categories"

feature:
  display_name: "Feature"
  group_list: "categories, labels"
  aliases:
    - "enhancement"
    - "feature-request"

issue:
  display_name: "Issue"
  group_list: "categories"

question:
  group_list: "categories"
  display_name: "Question"

# --------
# Feeds
# --------

twitter:
  display_name: "Twitter"
  group_list: "feeds, categories"

github:
  display_name: "Github"
  group_list: "feeds"

forum:
  display_name: "Forum"
  group_list: "feeds"

irc:
  display_name: "IRC"
  group_list: "feeds"

blog:
  display_name: "Blog"
  group_list: "feeds"

disqus:
  display_name: "Disqus"
  group_list: "feeds"

bithub:
  display_name: "Bithub"
  group_list: "feeds"
  props:
    levenshtein_treshold: "0"

meetup:
  display_name: "Meetup"
  group_list: "feeds"

stack_exchange:
  display_name: "StackExchange"
  group_list: "feeds"

facebook:
  display_name: "Facebook"
  group_list: "feeds"

foursquare:
  display_name: "Foursquare"
  group_list: "feeds"

yelp:
  display_name: "Yelp"
  group_list: "feeds"

# --------
# Types
# --------

### Twitter

tweet: {}

follow: {}

### Github

push: {}

commit: {}

fork: {}

pull_request: {}

create_event: {}

issue: {}

issue_comment: {}

issue_action: {}

commit_comment: {}

watch: {}

gollum_event: {}

pull_request_review_comment: {}

commit: {}

public: {}

create: {}

# issues states

open: {}

closed: {}

### Forum

post: {}

### Meetup

rsvp: {}

### StackExchange

question: {}

answer: {}

comment: {}

### Facebook

status: {}

#comment: {}

like: {}

#checkin: {}

### FourSquare

checkin: {}

### Yelp

### IRC

message: {}

### Other

uncategorized: {}
