canjs:
 display_name: "CanJS"
 aliases:
   - "canjs"
   - "can_js"
   - "#canjs"

canui:
  display_name: "CanUI"
  aliases:
    - "canui"

javascriptmvc:
  display_name: "JavascriptMVC"
  aliases:
    - "javascriptmvc"
    - "jmvc"
    - "java_script_mvc"
    - "general java_script_mvc"

donejs:
  display_name: "DoneJS"
  aliases:
    - "donejs"
    - "done_js"

stealjs:
  display_name: "StealJS"
  aliases:
    - "stealjs"
    - "steal_js"
    - "steal"
 
funcunit:
  display_name: "FuncUnit"
  aliases:
    - "funcunit"
    - "func_unit"
 
jquerypp:
  display_name: "jQuery++"
  aliases:
    - "jquerypp"
    - "j_querypp"
    - "jquery++"
    - "j_query++"

documentjs:
  display_name: "DocumentJS"
  aliases:
    - "documentjs"
    - "document_js"

testee:
  display_name: "Testee.js"
  aliases:
    - "testee"
    - "testeejs"
    - "testee_js"
    - "testee.js"

digest:
  display_name: "Digest"

twitter:
  display_name: "Twitter"

bug:
  display_name: "Bug"

comment:
  display_name: "Comment"

feature:
  display_name: "Feature"
  aliases:
    - "feature"
    - "enhancement"
    - "feature-request"

question:
  display_name: "Question"

article:
  display_name: "Article"

plugin:
  display_name: "Plugin"

app:
  display_name: "App"

code:
  display_name: "Code"

event:
  display_name: "Event"

chat:
  display_name: "Chat"
