canjs:
 - canjs
 - can_js

canui:
 - canui

javascriptmvc:
 - javascriptmvc
 - jmvc
 - java_script_mvc
 - general java_script_mvc

donejs:
 - donejs
 - done_js

stealjs:
 - stealjs
 - steal_js
 
funcunit:
 - funcunit
 - func_unit
 
jquerypp:
 - jquerypp
 - j_querypp
 - jquery++
 - j_query++
