# File: ~/bash_aliases
# Author: Oliver Michels <oliver.michels@gmx.net>
# Desc: Definition of some useful aliases for the bash

# Some common shortcuts for file-/directory commands
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias l='ls'
alias grep='grep --color=auto'

# Some common shortcuts for tools
alias j='jobs'
alias v='vim'

# Aliases for git
alias git='git --no-pager'
alias gs='git status'
alias gb='git branch -a --color'
alias gd='git diff --color'
alias gc='git commit'
alias ga='git add'
alias gl='git log --pretty=oneline'
alias gps='git push'
alias gpl='git pull'
alias gco='git checkout'
alias grm='git rm'
alias gmv='git mv'

# Aliases for common chmods
alias 000='chmod 000'
alias 644='chmod 644'
alias 755='chmod 755'

# Outdated aliases for Debian-based systems -> to be removed someday
#alias agu='sudo apt-get update'
#alias agg='sudo apt-get upgrade'
#alias agi='sudo apt-get install'
#alias acs='apt-cache search'

# Execute the last command as root
alias lr='sudo $(history | tail -n 2 | head -n 1 | sed -e "s/^[ ]*[0-9]*[ ]*//g")'

# Search for a process containing a given name
function pps() {
ps aux | grep "$@" | grep -v 'grep';
}
