- name: Initial setup
  hosts: testing
  user: root
  vars:
    domain: 'testing.bithub.com'
    env: 'testing'
    pg:
      version: '9.4'
    ruby:
      version: '2.1.2'
    bithub:
      project_path: '/home/bithub'
    pg_dump:
      path: '/db_backups/'
      dbname: 'bithub'
  roles:
    - { role: jessie,      tags: ['jessie'] }
    - { role: common,      tags: ['common'] }
    - { role: ssh,         tags: ['ssh'] }
    - { role: nodejs,      tags: ['nodejs'] }
    - { role: nginx,       tags: ['nginx'] }
    - { role: postgresql,  tags: ['postgresql'] }
    - { role: rabbitmq,    tags: ['rabbitmq'] }
    - { role: redis,       tags: ['redis'] }
    - { role: ruby,        tags: ['ruby'] }
    - { role: bithub_prod, tags: ['bithub'] }
    - { role: pg_dump,     tags: ['pgdump'] }
