- name: Bithub Vagrant Development
  hosts: all
  user: vagrant
  vars:
    hostname: "bithub.loc"
    rabbitmq:
      username: "bithub"
      vhost: "/bithub"
      password: "Ei7PhaaH"
    pg:
      version: "9.3"
      dbname: "bithub"
      username: "bithub"
      password: "Ei7PhaaH"
    bithub:
      username: "bithub"
      password: "Ei7PhaaH"
      project_path: "/vagrant"
      ruby_version: "2.1.2"
  roles:
    - { role: common,     tags: ["common"] }
    - { role: nginx,      tags: ["nginx"] }
    - { role: postgresql, tags: ["postgresql"] }
    - { role: rabbitmq,   tags: ["rabbitmq"] }
    - { role: redis,      tags: ["redis"] }
    - { role: nodejs,     tags: ["nodejs"] }
    - { role: bithub,     tags: ["bithub"] }
