- name: Bithub Vagrant Development
  hosts: all
  user: vagrant
  vars:
    hostname: "bithub.loc"
    rabbitmq:
      username: "bithub"
      vhost: "/bithub"
      password: "foobar"
    pg:
      version: "9.3"
      dbname: "bithub"
      username: "bithub"
    ruby:
      version: "2.1.1"
  roles:
    - { role: common,     tags: ["common"] }
    - { role: nginx,      tags: ["nginx"] }
    - { role: postgresql, tags: ["postgresql"] }
    - { role: rabbitmq,   tags: ["rabbitmq"] }
    - { role: redis,      tags: ["redis"] }
    - { role: ruby,       tags: ["ruby"] }