class Embed < ActiveRecord::Base
  include RabbitHelper::Sugar

  belongs_to :brand
  validates_uniqueness_of :name, :scope => [:brand_id]

  has_many :filters, dependent: :destroy
  has_many :presets, :class_name => "EmbedPreset"

  has_many :services, dependent: :destroy

  has_many :embed_entities
  has_many :entities, through: :embed_entities

  has_many :events, dependent: :delete_all

  after_create { notify_crawler(:start) }
  after_destroy { notify_crawler(:stop) }

  before_save :log_update_to_embed_events, if: :published_changed?
  before_destroy :log_destroy_to_embed_events

  def blocking_filters; filters.where(action: 'block').all; end
  def approving_filters; filters.where(action: 'approve').all; end
  def permissive?; approved_by_default; end
  def restrictive?; !approved_by_default; end

  def approved_entities(scope = nil)
    sql = 'embed_entities.is_approved_manually = TRUE OR (embed_entities.is_approved_automatically = TRUE AND embed_entities.is_approved_manually IS NULL)'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity)
  end

  def blocked_entities(scope = nil)
    sql = 'embed_entities.is_approved_manually = FALSE OR (embed_entities.is_approved_automatically = FALSE AND embed_entities.is_approved_manually IS NULL)'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity)
  end

  def pinned_entitites(scope = nil)
    sql = 'embed_entities.is_pinned = TRUE'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity)
  end
  
  def valid_services
    services.all.select { |s| s.service_config.valid? }
  end

  def moderate
    moderate_entities_with_default_setting
    moderate_entities_from_services_approved_by_default

    entities.update_all(updated_at: DateTime.now) # bust cache


    # apply filters
    filters.sorted_in_application_order.map do |f|
      # don't use pluck because it modifies the SQL SELECT query generated by textacular
      entity_ids = f.detected_entities('id').all.map { |e| e.id }
      if entities.where(id: entity_ids).update_all(updated_at: DateTime.now)
        embed_entities.where(entity_id: entity_ids).update_all(is_approved_automatically: f.resulting_state, updated_at: DateTime.now)
      end
    end.all?
  end

  def make_link_to(entity)
    determined_state = determine_state(entity)

    if (ee = embed_entities.where(:entity_id => entity.id).first)
      ee.update_attributes({
        :is_approved_automatically => determined_state.first,
        :decision => determined_state.last
      })
    else
      embed_entities.create({
        :is_approved_automatically => determined_state.first,
        :decision => determined_state.last,
        :entity => entity,
      })
    end
  end

  # ako hub-default == approved onda oni koji bi imali approved_automatically == false --> decision je 'deleted' 
  # ako hub-default == blocked onda oni koji bi imali approved_automatically == true --> decision je 'approved' 

  def determine_state(entity)
    decision = 'pending'
    initial_state = determine_default_approval(entity)

    state_according_to_filters = filters.sorted_in_application_order.select do |f|
      f.detects?(entity)
    end.reduce(initial_state) do |_,f|
      f.resulting_state
    end

    if approved_by_default == true && state_according_to_filters == false
      decision = 'deleted'
    elsif approved_by_default == false && state_according_to_filters == true
      decision = 'approved'
    end

    state = (state_according_to_filters.nil?) ? approved_by_default : state_according_to_filters

    [state, decision]
  end

  def determine_default_approval(entity)
    (entity.services.where(:approved_by_default => true).count > 0)
  end

  private

  def moderate_entities_from_services_approved_by_default
    services.where(:approved_by_default => true).each do |s|
      EmbedEntity.joins('JOIN service_entities ON service_entities.entity_id = embed_entities.entity_id').where('service_entities.service_id = ?', s.id).update_all(:is_approved_automatically => s.approved_by_default)
    end
  end
    
  def moderate_entities_with_default_setting
    embed_entities.update_all(is_approved_automatically: approved_by_default)
  end

  def log_update_to_embed_events
    EmbedEvent.log_attr_update! self, 'published'
  end

  def log_destroy_to_embed_events
    EmbedEvent.log_destroy! self
  end

  def notify_crawler(action)
    unless ENV['RAILS_ENV'] == 'test'
      Rails.logger.info "Publishing a command to crawler #{msg(action)}"
      x('x.crawler', chan_is_short_lived = true) do |xchange|
        xchange.publish((msg(action).to_json), routing_key: :config)
      end
    end
  end

  def msg(action)
    {
      brand: {
        id: brand.id,
        name: brand.name
      },
      embed: {
        id: id,
        name: name
      },
      signature: "embed_#{action}",
      action: action
    }
  end
end
