class Embed < ActiveRecord::Base
  include RabbitHelper::Sugar

  belongs_to :brand
  validates_uniqueness_of :name, :scope => [:brand_id]

  has_many :filters, dependent: :destroy
  has_many :presets, :class_name => "EmbedPreset"

  has_many :services, dependent: :destroy

  has_many :embed_entities
  has_many :entities, through: :embed_entities

  has_many :events, dependent: :delete_all

  before_save :log_update_to_embed_events, if: :published_changed?
  before_destroy :log_destroy_to_embed_events

  def blocking_filters; filters.where(action: 'block').all; end
  def approving_filters; filters.where(action: 'approve').all; end
  def permissive?; approved_by_default; end
  def restrictive?; !approved_by_default; end

  def approved_entities(scope = nil)
    sql = 'embed_entities.is_approved_manually = TRUE OR (embed_entities.is_approved_automatically = TRUE AND embed_entities.is_approved_manually IS NULL)'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity)
  end

  def blocked_entities(scope = nil)
    sql = 'embed_entities.is_approved_manually = FALSE OR (embed_entities.is_approved_automatically = FALSE AND embed_entities.is_approved_manually IS NULL)'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity)
  end

  def pinned_entitites(scope = nil)
    sql = 'embed_entities.is_pinned = TRUE'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity)
  end

  def moderate
    moderate_entities_with_default_setting
    moderate_entities_from_services_approved_by_default

    entities.update_all(updated_at: DateTime.now) # bust cache

    # apply filters
    filters.sorted_in_application_order.each do |f|

      # don't use pluck because it modifies the SQL SELECT query generated by textacular
      detected_entity_ids = f.detected_entities('id').all.map { |e| e.id }

      filter_is_applied = entities.where(id: entity_ids).update_all(updated_at: DateTime.now) &&
        embed_entities.where(entity_id: entity_ids).update_all(is_approved_automatically: f.resulting_state, updated_at: DateTime.now)

      entities.where(id: entity_ids).find_each do |e|
        Notifier.notify_client(:entity_moderated, { entity: e, embed: self, action: (f.resulting_state ? 'approved' : 'blocked')})
      end

      filter_is_applied
    end
  end

  def valid_services
    services.all.select { |s| s.service_config.valid? }
  end

  def make_link_to(entity)
    if (ee = embed_entities.where(:entity_id => entity.id).first)
      ee.update_attribute(:is_approved_automatically, determine_state(entity))
      ee
    else
      embed_entities.create(entity: entity, is_approved_automatically: determine_state(entity))
    end
  end

  def determine_state(entity)
    state_according_to_filters = filters\
      .sorted_in_application_order.select do|f|
      f.detects?(entity)
    end.reduce(determine_default_approval(entity)) do |s,f|
      f.resulting_state
    end

    (state_according_to_filters.nil?) ? approved_by_default : state_according_to_filters
  end

  def determine_default_approval(entity)
    (entity.services.where(:approved_by_default => true).count > 0) || approved_by_default
  end

  private
      

  def moderate_entities_from_services_approved_by_default
    services.where(:approved_by_default => true).each do |s|
      EmbedEntity.joins('JOIN service_entities ON service_entities.entity_id = embed_entities.entity_id').where('service_entities.service_id = ?', s.id).update_all(:is_approved_automatically => s.approved_by_default)
    end
  end
    
  def moderate_entities_with_default_setting
    embed_entities.update_all(is_approved_automatically: approved_by_default)
  end

  def log_update_to_embed_events
    EmbedEvent.log_attr_update! self, 'published'
  end

  def log_destroy_to_embed_events
    EmbedEvent.log_destroy! self
  end
end
