class Embed < ActiveRecord::Base
  include Traits::AmqpDeclaration

  belongs_to :brand
  validates_uniqueness_of :name, :scope => [:brand_id]

  has_many :filters, dependent: :destroy
  has_many :presets, :class_name => "EmbedPreset"

  has_many :services, dependent: :destroy

  has_many :embed_entities
  has_many :entities, through: :embed_entities

  has_many :events, dependent: :delete_all

  after_create { notify_crawler(:start) }
  after_destroy { notify_crawler(:stop) }

  def clear_relations_and_destroy
    embed_id = id

    query = <<-SQL

    -- delete service_entities that are no longer
    -- valid as (because the services are going to be deleted)
    ------------------------------------------------------------------------------
    delete from service_entities using embed_entities
    where service_entities.entity_id = embed_entities.entity_id
    and service_id in (select id from services where embed_id = #{embed_id});

    -- delete connections between entities and the embed we're deleting
    -------------------------------------------------------------------
    delete from embed_entities
    where embed_id = #{embed_id};

    -- delete entities that have no connections to an embed
    -------------------------------------------------------
    delete from entities
    where id not in (select distinct(entity_id) from embed_entities);

    -- delete events that belong to this embed
    ------------------------------------------
    delete from events
    where embed_id = #{embed_id};

    SQL

    ActiveRecord::Base.transaction do
      ActiveRecord::Base.connection.execute(query)
    end

    destroy
  end

  def blocking_filters; filters.where(action: 'block').all; end
  def approving_filters; filters.where(action: 'approve').all; end
  def permissive?; approved_by_default; end
  def restrictive?; !approved_by_default; end

  def approved_entities(scope = nil)
    sql = 'embed_entities.is_approved_manually = TRUE OR embed_entities.is_approved_automatically = TRUE'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity)
  end

  def blocked_entities(scope = nil)
    sql = 'embed_entities.is_approved_manually = FALSE OR embed_entities.is_approved_automatically = FALSE'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity) 
  end

  def pinned_entitites(scope = nil)
    sql = 'embed_entities.is_pinned = TRUE'
    scope ? scope.where(sql) : embed_entities.where(sql).map(&:entity) 
  end

  def moderate
    EmbedEntity.where({embed_id: self.id})
      .update_all(is_approved_automatically: approved_by_default)
    
    filters.sorted_in_application_order.each do |f|
      # don't use pluck because it modifies the SQL SELECT query generated by textacular
      entity_ids = f.detected_entities('id').all.map { |e| e.id }
      EmbedEntity\
        .where({embed_id: self.id, entity_id: entity_ids})\
        .update_all(is_approved_automatically: true)
    end
  end

  def valid_services
    services.all.select { |s| s.service_config.valid? }
  end

  def make_link_to(entity)
    ee = embed_entities.build \
      entity: entity,
      is_approved_automatically: determine_state(entity)

    ee.save
  end

  def determine_state(entity)
    state_according_to_filters = filters\
      .sorted_in_application_order.select do|f|
      f.detects?(entity)
    end.reduce(approved_by_default) do |s,f|
      f.resulting_state
    end

    (state_according_to_filters.nil?) ? approved_by_default : state_according_to_filters
  end
  
  private

  def notify_crawler(action)
    unless ENV['RAILS_ENV'] == 'test'
      Rails.logger.info "Publishing a command to crawler #{msg(action)}"
      x('x.crawler').publish((msg(action).to_json), routing_key: :config)
    end
  end

  def msg(action)
    {
      brand: {
        id: brand.id,
        name: brand.name
      },
      embed: {
        id: id,
        name: name
      },
      signature: "embed_#{action}",
      action: action
    }
  end
end
