class Hub < ActiveRecord::Base
  ModerationState = Struct.new(:state, :decision)

  belongs_to :brand
  validates_uniqueness_of :name, :scope => [:brand_id]

  has_many :filters, dependent: :destroy
  has_many :embeds, :class_name => "HubEmbed"

  has_many :services, dependent: :destroy

  has_many :moderations
  has_many :bits, through: :moderations

  has_many :events, dependent: :delete_all

  before_save :log_update_to_hub_events, if: :published_changed?
  before_destroy :log_destroy_to_hub_events

  def blocking_filters; filters.where(action: 'block').all; end
  def approving_filters; filters.where(action: 'approve').all; end
  def permissive?; approved_by_default; end
  def restrictive?; !approved_by_default; end

  def approved_bits(scope = nil)
    sql = 'moderations.is_approved_manually = TRUE OR (moderations.is_approved_automatically = TRUE AND moderations.is_approved_manually IS NULL)'
    scope ? scope.where(sql) : moderations.where(sql).map(&:bit)
  end

  def blocked_bits(scope = nil)
    sql = 'moderations.is_approved_manually = FALSE OR (moderations.is_approved_automatically = FALSE AND moderations.is_approved_manually IS NULL)'
    scope ? scope.where(sql) : moderations.where(sql).map(&:bit)
  end

  def pinned_entitites(scope = nil)
    sql = 'moderations.is_pinned = TRUE'
    scope ? scope.where(sql) : moderations.where(sql).map(&:bit)
  end
  
  def valid_services
    services.all.select { |s| s.service_config.valid? }
  end

  def moderate
    moderate_bits_with_default_setting
    approve_bits_from_services_approved_by_default
        
    ActiveRecord::Base.connection.execute(
      <<-SQL
update moderations ee
  set decision = 'approved'
  from hubs e 
  where ee.bit_id = e.id
  and ee.decision = 'pending'
  and e.approved_by_default = TRUE;
      SQL
    )

    ActiveRecord::Base.connection.execute(
      <<-SQL
update moderations ee
  set decision = 'approved'
  from services s
  where ee.hub_id = s.hub_id
  and ee.decision = 'pending'
  and s.approved_by_default = TRUE;
      SQL
    )

    # apply filters
    filters.sorted_in_application_order.each do |f|

      # don't use pluck because it modifies the SQL SELECT query generated by textacular

      bit_ids = f.detected_bits('id').all.map { |e| e.id }

      if bits.where(id: bit_ids).update_all(updated_at: DateTime.now)
        moderations
          .where(bit_id: bit_ids)
          .update_all({
          updated_at: DateTime.now,
          decision: f.resulting_decision,
          is_approved_automatically: f.resulting_state
        })
      end

      bits.where(id: bit_ids).find_each do |e|
        Notifier.notify_client(:bit_moderated, { bit: e, hub: self, action: (f.resulting_state ? 'approved' : 'blocked')})
      end
    end
  end

  def make_link_to(bit)
    determined_state = determine_state(bit)

    if (ee = moderations.where(:bit_id => bit.id).first)
      ee.update_attributes({
        :is_approved_automatically => determined_state.state,
        :decision => determined_state.decision,
      })
      ee
    else
      moderations.create({
        :is_approved_automatically => determined_state.state,
        :decision => determined_state.decision,
        :bit => bit,
      })
    end
  end

  def determine_state(bit)
    initial_state = determine_default_approval(bit)

    resulting_state = filters.sorted_in_application_order.select do |f|
      f.detects?(bit)
    end.reduce(initial_state) do |_, f|
      ModerationState.new(f.resulting_state, f.resulting_decision)
    end

    resulting_state.decision = 'approved' if (resulting_state.decision == 'pending' && resulting_state.state) # Switch to approved if either service or hub are approved by default
    resulting_state
  end

  def determine_default_approval(bit)
    service = (bit.services.where(:approved_by_default => true).count > 0) ? 1 : 0
    hub = approved_by_default ? 1 : 0

    ModerationState.new((service + hub > 0), 'pending')
  end

  private
      

  def approve_bits_from_services_approved_by_default
    services.where(:approved_by_default => true).each do |s|
      Moderation.joins('JOIN service_bits ON service_bits.bit_id = moderations.bit_id')
        .where('service_bits.service_id = ?', s.id)
        .update_all(:is_approved_automatically => s.approved_by_default, decision: 'approved')
    end
  end
    
  def moderate_bits_with_default_setting
    moderations.update_all(
      is_approved_automatically: approved_by_default,
      updated_at: DateTime.now,
      decision: 'pending'
    )
  end

  def log_update_to_hub_events
    HubEvent.log_attr_update! self, 'published'
  end

  def log_destroy_to_hub_events
    HubEvent.log_destroy! self
  end
end
