- name: Create backups directory
  file: path={{ pg_dump.path }} state=directory owner=postgres

- name: Upload bash script
  template: src=pg_dump.sh dest=/opt/ mode=0755

- name: Execute dump script
  command: /opt/pg_dump.sh
  sudo: yes
  sudo_user: 'postgres'

- name: Create crontab job
  cron: name="Dump {{ pg_dump.dbname }} to {{ pg_dump.path }}" hour="2,14" job="/opt/pg_dump.sh" user=postgres
