- name: Replace sources.list
  copy: src=sources.list dest=/etc/apt/sources.list

- name: Update packages
  apt: update_cache=yes

- name: Safe-upgrade packages
  apt: upgrade=safe

- name: Install systemd
  apt: name={{ item }} state=installed
  with_items:
    - systemd
    - systemd-sysv
